[workspace]
members = ["crypto"]

[workspace.package]
authors = ["Jisu-Woniu"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Jisu-Woniu/digital-signature/"
version = "1.3.0"

[package]
name = "digital-signature"
description = "A Tauri app for signing files"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = { version = "1.0.87", features = ["backtrace"] }
digital-signature-crypto = { path = "crypto" }
futures = "0.3.29"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tauri = { version = "2.0.1", features = ["config-toml"] }
tauri-plugin-dialog = "2.0.1"
tokio = { version = "1.40.0", features = ["fs"] }

[dev-dependencies]
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
