[workspace]
members = ["crypto"]

[workspace.package]
authors = ["Jisu-Woniu"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Jisu-Woniu/digital-signature/"
version = "0.1.0"

[package]
name = "digital-signature"
description = "A Tauri app for signing files"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
futures = "0.3.29"
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["fs"] }

[dependencies.digital-signature-crypto]
path = "crypto"
version = "0.1.0"

[dependencies.tauri]
features = [
    "config-toml",
    "dialog-ask",
    "dialog-confirm",
    "dialog-message",
    "dialog-open",
    "icon-ico",
    "icon-png",
]
version = "1.5.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dev-dependencies]
tokio = { version = "1.34.0", features = ["rt-multi-thread"] }
