[workspace]
members = ["crypto"]

[workspace.package]
authors = ["Jisu-Woniu"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Jisu-Woniu/digital-signature/"
version = "1.1.0"

[package]
name = "digital-signature"
description = "A Tauri app for signing files"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
digital-signature-crypto = { path = "crypto" }
futures = "0.3.29"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["fs"] }

[dependencies.tauri]
features = [
  "config-toml",
  "dialog-message",
  "dialog-open",
  "icon-ico",
  "icon-png",
]
version = "1.5.2"

[dev-dependencies]

[dev-dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.34.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
