[package]
name = "digital-signature"
version = "0.1.0"
description = "A Tauri app for signing files"
authors = ["Jisu-Woniu"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"

[dependencies.tauri]
version = "1.5.2"
features = [
    "dialog-confirm",
    "dialog-message",
    "dialog-ask",
    "dialog-open"]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
