productName = "digital-signature"
mainBinaryName = "digital-signature"
version = "1.3.0"
identifier = "digital-signature"

[build]
beforeBuildCommand = "pnpm build"
beforeDevCommand = "pnpm dev"
frontendDist = "../dist"
devUrl = "http://127.0.0.1:1420"

[bundle]
active = true
category = "Utility"
copyright = "Copyright (c) 2023-2024 Jisu-Woniu"
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
shortDescription = "A Tauri app for signing files."

[bundle.windows.nsis]
displayLanguageSelector = true
installMode = "both"
languages = ["SimpChinese", "English"]

[bundle.windows.wix]
language = ["zh-CN", "en-US"]

[plugins]

[app]
withGlobalTauri = false

[[app.windows]]
label = "main"
title = "数字签名工具"
fullscreen = false
resizable = true
width = 800
height = 600
