[build]
beforeBuildCommand = "pnpm build"
beforeDevCommand = "pnpm dev"
devPath = "http://127.0.0.1:1420"
distDir = "../dist"
withGlobalTauri = false

[package]
productName = "digital-signature"
version = "1.2.0"

[tauri]

[tauri.allowlist]

[tauri.allowlist.dialog]
message = true
open = true

[tauri.bundle]
active = true
category = "Utility"
copyright = "Copyright (c) 2023 Jisu-Woniu"
targets = "all"
identifier = "digital-signature"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
shortDescription = "A Tauri app for signing files."

[tauri.bundle.windows]

[tauri.bundle.windows.webviewInstallMode]
type = "embedBootstrapper"

[tauri.bundle.windows.nsis]
displayLanguageSelector = true
installMode = "both"
languages = ["SimpChinese", "English"]

[tauri.bundle.windows.wix]
language = ["zh-CN", "en-US"]

[[tauri.windows]]
label = "main"
title = "数字签名工具"

fullscreen = false
resizable = true
width = 800
height = 600
