[package]
name = "crypto"
version.workspace = true
authors.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ed25519 = { version = "2.2.3", features = ["pkcs8", "pem"] }
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
rand = "0.8.5"
signature = { version = "2.1.0", features = ["digest"] }
thiserror = "1.0.50"

[dependencies.tokio]
version = "1.33.0"
features = ["rt-multi-thread", "fs", "io-util", "macros"]
