[package]
name = "digital-signature-crypto"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1.83"
chrono = "0.4.39"
futures = "0.3.31"
hex = "0.4.3"
pgp = "0.14.2"
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
smallvec = "1.13.2"
thiserror = "2.0.6"
tokio-util = { version = "0.7.13", features = ["io-util"] }
zeroize = "1.8.1"

[dependencies.tokio]
features = ["fs", "io-util"]
version = "1.42.0"

[dev-dependencies]
temp-dir = "0.1.14"

[dev-dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.42.0"
