[package]
name = "crypto"
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
hex = "0.4.3"
# ed25519 = { version = "2.2.3", features = ["pkcs8", "pem"] }
# ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
pgp = "0.10.2"
smallvec = "1.11.2"
# rand = "0.8.5"
# signature = { version = "2.1.0", features = ["digest"] }
thiserror = "1.0.50"
zeroize = "1.6.0"

[dependencies.tokio]
version = "1.33.0"
features = ["rt-multi-thread", "fs", "io-util", "macros"]
