[package]
name = "digital-signature-crypto"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-trait = "0.1.74"
chrono = "0.4.31"
hex = "0.4.3"
pgp = "0.10.2"
serde = { version = "1.0.193", features = ["derive"] }
smallvec = "1.11.2"
thiserror = "1.0.50"
zeroize = "1.7.0"
tokio-util = { version = "0.7.10", features = ["io-util"] }

[dependencies.tokio]
features = ["fs", "io-util", "macros", "rt-multi-thread"]
version = "1.34.0"

[dev-dependencies]
temp-dir = "0.1.11"
