name: test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-20.04
          - windows-latest

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install frontend dependencies with pnpm
        run: pnpm install
      - name: Setup Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
      - name: Install dependencies on Ubuntu
        if: ${{ startsWith(matrix.platform, 'ubuntu') }}
        run: |
          sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Run Rust unit tests
        working-directory: ./src-tauri
        run: cargo test --workspace
      - id: tauri
        name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ join(fromJson(steps.tauri.outputs.artifactPaths), fromJson('"\n"')) }}
