name: "publish"
on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies on Ubuntu
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use
      - id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "v__VERSION__"
          releaseBody: "**Full Changelog**: https://github.com/Jisu-Woniu/digital-signature/commits/v__VERSION__"
          releaseDraft: true
          prerelease: false
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.tauri.outputs.artifactPaths }}
