name: "publish"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies on Ubuntu
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__-unreleased # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "v__VERSION__-unreleased"
          releaseBody: "**Full Changelog**: https://github.com/Jisu-Woniu/digital-signature/commits/main"
          releaseDraft: true
          prerelease: false
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ join(fromJson(steps.tauri.outputs.artifactPaths), fromJson('"\n"')) }}
